# Generated by Django 5.1.5 on 2025-03-27 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindvswild', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
