# Generated by Django 5.1.5 on 2025-03-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindvswild', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='invite_code',
        ),
    ]
