name: Deploy Django + Vue.js

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
      - name: Deploying Django + Vue.js app
        run: |
          cd /home/django/project
          
          if [ -d "./app" ]; then
            cd ./app
            git pull origin main
          else
            git clone https://github.com/HE-Arc/Mind-vs-Wild.git app
            cd ./app
          fi
          
          export PIPENV_VENV_IN_PROJECT=1
          pipenv --python $(which python3)
          pipenv install --deploy --ignore-pipfile
          
          # Vérifier que Django est bien installé
          pipenv run python -m django --version
          
          pipenv run python manage.py migrate --noinput
          pipenv run python manage.py collectstatic --noinput
          
          cd ../frontend
          npm install
          npm run build
          cd ..
          
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
          
          echo "Success"
