name: Deploy Django + Vue.js

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - name: Deploying Django + Vue.js app
        run: |
          cd /home/django/project
          
          if [ -d "./app" ]; then
            cd app
            git pull origin main
          else
            git clone https://github.com/HE-Arc/Mind-vs-Wild.git app
            cd app
          fi
          
          # --- Django part ---
          cd api
          export PIPENV_VENV_IN_PROJECT=1
          export PIPENV_IGNORE_VIRTUALENVS=1
          pipenv --rm || true
          pipenv --python $(which python3)
          pipenv install --deploy --ignore-pipfile
          
          pipenv run python manage.py migrate --noinput
          pipenv run python manage.py collectstatic --noinput

          # --- Frontend part ---
          cd ../frontend
          export NODE_OPTIONS="--max-old-space-size=1024"
          npm install
          npm run build
          
          # --- Restart services ---
          cd ..
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx

          echo "Success"
