name: Deploy Django + Vue.js

on:
  push:
    branches:
      - main

jobs:
  Update_Code:
    runs-on: self-hosted
    steps:
      - name: Checkout or update code
        run: |
          cd /home/django/project
          if [ -d "./app" ]; then
            cd app
            git pull origin main
          else
            git clone https://github.com/HE-Arc/Mind-vs-Wild.git app
          fi

  Deploy_Django:
    runs-on: self-hosted
    needs: Update_Code
    steps:
      - name: Deploy Django backend
        run: |
          cd /home/django/project/app/api
          python3 -m venv /home/django/project/app/api/venv
          source /home/django/project/app/api/venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

  Deploy_Frontend:
    runs-on: self-hosted
    needs: Update_Code
    steps:
      - name: Deploy Quasar frontend
        run: |
          cd /home/django/project/app/frontend
          npm install
          npm run build
          echo "Frontend built successfully."

  Restart_Services:
    runs-on: self-hosted
    needs: [Deploy_Django, Deploy_Frontend]
    steps:
      - name: Restart Gunicorn and Nginx
        run: |
          sudo systemctl restart gunicorn
